name: Docker Image test & CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -t ifakaowoh/docker-react -f Dockerfile.dev .
        docker run ifakaowoh/docker-react npm run test
